# Site settings
title: Diário do Fusca
email: vilar@me.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: feelsen
github_username:  sergiovilar
disqus_shortname: diriodofusca

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"
permalink: /:categories/:title.html

category_archive:
  slugify: true
  path: /category

tag_archive:
  slugify: true
  path: /tag
