# Site settings
title: Diário do Fusca
email: vilar@me.com
description: Aventuras de um Fusca 79.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://diariodofusca.com" # the base hostname & protocol for your site
twitter_username: feelsen
github_username:  sergiovilar
disqus_shortname: diriodofusca

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"
permalink: /:categories/:title.html

category_archive:
  slugify: true
  path: /category

tag_archive:
  slugify: true
  path: /tag
